# Generated by Django 5.1.7 on 2025-04-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('helloText', models.TextField()),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English')], default='fa', max_length=25)),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=25)),
                ('logooo', models.ImageField(upload_to='test/')),
                ('header', models.ImageField(upload_to='test/')),
            ],
        ),
    ]
