# Generated by Django 5.1.7 on 2025-04-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_sitemenu_aboutme_githublink_aboutme_linkedinlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemenu',
            name='title_en',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitemenu',
            name='icon',
            field=models.ImageField(upload_to='icons/'),
        ),
    ]
